markdown: rdiscount
pygments: true
permalink: /posts/:title
rdiscount:
  extensions: [smart]
exclude: [ Gemfile, Gemfile.lock, gems, _assets, bower_components ]
title : Harish Vasudevasarma
production_url : hvsarma.github.io
description: "All about statistics and machine learning from Harish Vasudevasarma"
disqus_shortname: 
analytics: UA-36900153-4
gauges: 50f2b533613f5d7c8000000c
author :
  name : Harish Vasudevasarma
  github : hvsarma
  twitter : tboardingpass
  email: hvasudevasarma@gmail.com
